/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nathan
 */
public class boletos extends javax.swing.JFrame {

    private conectar bd;
    private DefaultTableModel tBol;
    /**
     * Creates new form boletos
     */
    public boletos(conectar BD) {
        bd = BD;
        tBol = (DefaultTableModel) boletoTab.getModel();
        preencheTabel();
        initComponents();
    }

    private boletos() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        guardarBt = new javax.swing.JToggleButton();
        limparBt = new javax.swing.JToggleButton();
        rPago = new javax.swing.JRadioButton();
        rPagar = new javax.swing.JRadioButton();
        rVencido = new javax.swing.JRadioButton();
        mesTX = new javax.swing.JFormattedTextField();
        aluguelTX = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        boletoTab = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.lightGray);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Boletos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 18), new java.awt.Color(51, 51, 51))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Aluguel");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Mês");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Situação");

        guardarBt.setBackground(new java.awt.Color(241, 242, 244));
        guardarBt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        guardarBt.setForeground(new java.awt.Color(51, 0, 51));
        guardarBt.setText("Guardar");
        guardarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtActionPerformed(evt);
            }
        });

        limparBt.setBackground(new java.awt.Color(241, 242, 244));
        limparBt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        limparBt.setForeground(new java.awt.Color(51, 0, 51));
        limparBt.setText("↺");
        limparBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparBtActionPerformed(evt);
            }
        });

        buttonGroup1.add(rPago);
        rPago.setText("Pago");

        buttonGroup1.add(rPagar);
        rPagar.setText("A pagar");

        buttonGroup1.add(rVencido);
        rVencido.setText("Vencido");

        mesTX.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        aluguelTX.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        aluguelTX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aluguelTXActionPerformed(evt);
            }
        });

        boletoTab.setAutoCreateRowSorter(true);
        boletoTab.setFont(new java.awt.Font("DejaVu Serif", 0, 14)); // NOI18N
        boletoTab.setForeground(java.awt.Color.black);
        boletoTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Nome", "Telefone", "CPF", "Excluir", "Alterar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        boletoTab.setToolTipText("");
        boletoTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boletoTabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(boletoTab);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(guardarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(limparBt, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rPago)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rPagar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rVencido))
                            .addComponent(mesTX, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aluguelTX, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(aluguelTX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(mesTX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(guardarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(limparBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(rPago)
                                    .addComponent(rPagar)
                                    .addComponent(rVencido)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(191, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtActionPerformed
        int confirma;
        confirma = JOptionPane.showConfirmDialog(null, "Deseja Gravar esses dados?");
        if (confirma == JOptionPane.YES_OPTION) {
            String alu, mes, sit = null;
            alu = aluguelTX.getText();
            mes = mesTX.getText();
            if (rPago.isSelected())
                sit = "Pago";
            else if (rPagar.isSelected())
                sit = "A pagar";
            else if (rVencido.isSelected())
                   sit = "Vencido";
           
            conectar aa = new conectar();
            try {
                if(idSelect.equals("")){
                    bd.persistir("INSERT INTO tb_boletos(aluguel, mes, situacao) "
                        + "VALUES('" + alu + "','" + mes + "','" + sit + "')");
                    JOptionPane.showMessageDialog(null, "Gravado com sucesso!");

                }else{
                    bd.persistir("update tb_boletos set "
                        + "aluguel = '" + alu + "'"
                        + ",mes = '" + mes + "'"
                        + ",sit = '" + sit + "' "
                        + "where id = '"+idSelect+"'");
                    JOptionPane.showMessageDialog(null, "Editado com sucesso!");
                }
                preencheTabel();

            } catch (Exception ex) {
                System.out.println(ex.getMessage()+" ERROR-BD");
            }

        }
        else {
            JOptionPane.showMessageDialog(null, "Cancelado!");
        }
    }//GEN-LAST:event_guardarBtActionPerformed

    private void limparBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparBtActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_limparBtActionPerformed

    private void aluguelTXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aluguelTXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aluguelTXActionPerformed

    private void boletoTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boletoTabMouseClicked
        int li = boletoTab.getSelectedRow();
        int col = boletoTab.getSelectedColumn();
        String texto = (String) boletoTab.getValueAt(li, col);
        String id = (String) boletoTab.getValueAt(li, 0);
        //idSelect = "";
        if(texto.equals("            X")){
            excluir(id);
        }else if(texto.equals("            O")){
            editar(id);
        }
        preencheTabel();
    }//GEN-LAST:event_boletoTabMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(boletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(boletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(boletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(boletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new boletos().setVisible(true);
            }
        });
    }
    
    
    public ResultSet busca() {
        return bd.recupera("select * from tb_boletos");
    }
    
    public void limpar() {
        this.idSelect = "";
        this.aluguelTX.setText("");
        this.mesTX.setText("");
    }
    public void excluir(String id){
        bd.persistir("DELETE FROM tb_boletos where id = "+id);
        limpar();
    }
    public void editar(String id){
        ResultSet boletos;
        try{
        boletos =  bd.recupera("SELECT * FROM tb_boletos where id = "+id);
        while(boletos.next()){
            this.idSelect = boletos.getString("id");
            this.aluguelTX.setText(boletos.getString("aluguel"));
            this.mesTX.setText(boletos.getString("mes"));
        }
            
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }
    
    
    public void preencheTabel() {
        try {
            ResultSet todos = bd.recupera("select * from tb_boletos");
            tBol.setNumRows(0);
            while (todos.next()) {
                String[] Nlinha = {
                    todos.getString("aluguel"),
                    todos.getString("mes"),
                    todos.getString("situacao"),
                    "            X", "            O"
                };
                tBol.addRow(Nlinha);
            }
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField aluguelTX;
    private javax.swing.JTable boletoTab;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton guardarBt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton limparBt;
    private javax.swing.JFormattedTextField mesTX;
    private javax.swing.JRadioButton rPagar;
    private javax.swing.JRadioButton rPago;
    private javax.swing.JRadioButton rVencido;
    // End of variables declaration//GEN-END:variables
private String idSelect = "";
}
