/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estacionamento;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author nathan
 */
public class boletos extends javax.swing.JPanel {

    /**
     * Creates new form boletos
     */
    private conectar bd;
    
    public boletos(conectar BD) {
        bd = BD;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rPago = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rPagar = new javax.swing.JRadioButton();
        limparBt = new javax.swing.JToggleButton();
        guardarBt1 = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rVencido = new javax.swing.JRadioButton();
        aluguelTX = new javax.swing.JFormattedTextField();
        mesCBX = new javax.swing.JComboBox<>();

        setBackground(java.awt.Color.lightGray);
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Boletos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 18))); // NOI18N

        buttonGroup1.add(rPago);
        rPago.setText("Pago");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Aluguel");

        buttonGroup1.add(rPagar);
        rPagar.setText("A pagar");

        limparBt.setBackground(new java.awt.Color(241, 242, 244));
        limparBt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        limparBt.setForeground(new java.awt.Color(51, 0, 51));
        limparBt.setText("↺");
        limparBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparBtActionPerformed(evt);
            }
        });

        guardarBt1.setBackground(new java.awt.Color(241, 242, 244));
        guardarBt1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        guardarBt1.setForeground(new java.awt.Color(51, 0, 51));
        guardarBt1.setText("Guardar");
        guardarBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBt1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Situação");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Mês");

        buttonGroup1.add(rVencido);
        rVencido.setText("Vencido");

        aluguelTX.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        aluguelTX.setText("R$ ");
        aluguelTX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aluguelTXActionPerformed(evt);
            }
        });

        mesCBX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        mesCBX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesCBXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(guardarBt1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(limparBt, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rPago)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rPagar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rVencido))
                            .addComponent(aluguelTX, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mesCBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(aluguelTX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(mesCBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guardarBt1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(limparBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(rPago)
                        .addComponent(rPagar)
                        .addComponent(rVencido)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void limparBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparBtActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_limparBtActionPerformed

    private void guardarBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBt1ActionPerformed
        int confirma;
        confirma = JOptionPane.showConfirmDialog(null, "Deseja Gravar esses dados?");
        if (confirma == JOptionPane.YES_OPTION) {
            String alu, sit = null;
            alu = aluguelTX.getText();
            //mes = mesTX.getText();
            if (rPago.isSelected())
            sit = "Pago";
            else if (rPagar.isSelected())
            sit = "A pagar";
            else if (rVencido.isSelected())
            sit = "Vencido";

            conectar aa = new conectar();
            try {
                if(idSelect.equals("")){
                    bd.persistir("INSERT INTO boletos(aluguel, mes, situacao) "
                        + "VALUES('" + alu + "','" + (String)mesCBX.getSelectedItem() + "','" + sit + "')");
                    JOptionPane.showMessageDialog(null, 
                            
                            "Boleto Gravado com sucesso!\n"+
                            "Aluguel: "+alu+
                            "\nMês: "+(String)mesCBX.getSelectedItem()+
                            "\nSituação: "+sit
                    );

                }else{
                    bd.persistir("update boletos set "
                        + "aluguel = '" + alu + "'"
                        + ",mes = '" + (String)mesCBX.getSelectedItem() + "'"
                        + ",sit = '" + sit + "' "
                        + "where id = '"+idSelect+"'");
                    JOptionPane.showMessageDialog(null, "Editado com sucesso!");
                }
                //preencheTabel();

            } catch (Exception ex) {
                System.out.println(ex.getMessage()+" ERROR-BD");
            }

        }
        else {
            JOptionPane.showMessageDialog(null, "Cancelado!");
        }
    }//GEN-LAST:event_guardarBt1ActionPerformed

    private void aluguelTXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aluguelTXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aluguelTXActionPerformed

    private void mesCBXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesCBXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesCBXActionPerformed
   
    public ResultSet busca() {
        return bd.recupera("select * from tb_clientes");
    }
    
    public void limpar() {
        this.idSelect = "";
        this.aluguelTX.setText("");
        this.mesCBX.setSelectedItem("Janeiro");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField aluguelTX;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton guardarBt1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JToggleButton limparBt;
    private javax.swing.JComboBox<String> mesCBX;
    private javax.swing.JRadioButton rPagar;
    private javax.swing.JRadioButton rPago;
    private javax.swing.JRadioButton rVencido;
    // End of variables declaration//GEN-END:variables
private String idSelect = "";
}
