/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estacionamento;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nathan
 */
public class clientes extends javax.swing.JPanel {

       private conectar bd;

       private DefaultTableModel tCli;
    /**
     * Creates new form clientes
     */
    public clientes(conectar BD) {
        bd = BD;
        initComponents();
        tCli = (DefaultTableModel) clienteTab.getModel();
        preencheTabel();
    }

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomeTex = new javax.swing.JTextField();
        telText = new javax.swing.JTextField();
        cpfTex = new javax.swing.JTextField();
        guardarBt = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        clienteTab = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        limparBt = new javax.swing.JToggleButton();

        homeP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 18), new java.awt.Color(51, 51, 51))); // NOI18N
        homeP.setToolTipText("");
        homeP.setPreferredSize(new java.awt.Dimension(812, 401));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Nome");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Telefone");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("CPF");

        nomeTex.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        telText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        cpfTex.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        guardarBt.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        guardarBt.setForeground(new java.awt.Color(51, 0, 51));
        guardarBt.setText("Guardar");
        guardarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtActionPerformed(evt);
            }
        });

        clienteTab.setAutoCreateRowSorter(true);
        clienteTab.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        clienteTab.setForeground(java.awt.Color.black);
        clienteTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Nome", "Telefone", "CPF", "Excluir", "Alterar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        clienteTab.setToolTipText("");
        clienteTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clienteTabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(clienteTab);

        btnVoltar.setText("Voltar");
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarMouseClicked(evt);
            }
        });

        limparBt.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        limparBt.setForeground(new java.awt.Color(51, 0, 51));
        limparBt.setText("Limpar");
        limparBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout homePLayout = new javax.swing.GroupLayout(homeP);
        homeP.setLayout(homePLayout);
        homePLayout.setHorizontalGroup(
            homePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePLayout.createSequentialGroup()
                .addGroup(homePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePLayout.createSequentialGroup()
                        .addGroup(homePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(homePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomeTex, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(telText, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(cpfTex, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)))
                    .addGroup(homePLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(guardarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(limparBt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(homePLayout.createSequentialGroup()
                .addGap(724, 724, 724)
                .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        homePLayout.setVerticalGroup(
            homePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(homePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeTex, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(homePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(8, 8, 8)
                .addGroup(homePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfTex, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(homePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limparBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(homePLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(btnVoltar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(homeP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void limparBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparBtActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_limparBtActionPerformed

    private void btnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseClicked
        // TODO add your handling code here:
        this.homeP.setVisible(false);

    }//GEN-LAST:event_btnVoltarMouseClicked

    private void clienteTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteTabMouseClicked
        int li = clienteTab.getSelectedRow();
        int col = clienteTab.getSelectedColumn();
        String texto = (String) clienteTab.getValueAt(li, col);
        String id = (String) clienteTab.getValueAt(li, 0);
        //idSelect = "";
        if(texto.equals("            X")){
            excluir(id);
        }else if(texto.equals("            O")){
            editar(id);
        }
        preencheTabel();
    }//GEN-LAST:event_clienteTabMouseClicked

    private void guardarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtActionPerformed
        int confirma;
        confirma = JOptionPane.showConfirmDialog(null, "Deseja Gravar esses dados?");
        if (confirma == JOptionPane.YES_OPTION) {
            // verifica se o usuário clicou no botão YES
            String cli, tell, cpf;
            cli = nomeTex.getText();
            tell = telText.getText();
            cpf = cpfTex.getText();
            conectar bb = new conectar();

            try {

                if(idSelect.equals("")){
                    bd.persistir("INSERT INTO tb_clientes(nome, telefone, cpf) "
                        + "VALUES('" + cli + "','" + tell + "','" + cpf + "')");

                    JOptionPane.showMessageDialog(null, "Gravado com sucesso!");
                }else{
                    bd.persistir("update tb_clientes set "
                        + "nome = '" + cli + "'"
                        + ",telefone = '" + tell + "'"
                        + ",cpf = '" + cpf + "' "
                        + "where id = '"+idSelect+"'");
                    JOptionPane.showMessageDialog(null, "Editado com sucesso!");
                }
                preencheTabel();

            } catch (Exception ex) {
                System.out.println(ex.getMessage()+" ERROR");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Cancelado!");
        }

    }//GEN-LAST:event_guardarBtActionPerformed
public void excluir(String id){
        bd.persistir("DELETE FROM tb_clientes where id = "+id);
        limpar();
//        this.idSelect = "";
//        this.nomeTex.setText("");
//        this.telText.setText("");
//        this.cpfTex.setText("");
    }
    public void editar(String id){
        ResultSet cliente;
        try{
        cliente =  bd.recupera("SELECT * FROM tb_clientes where id = "+id);
        while(cliente.next()){
            this.idSelect = cliente.getString("id");
            this.nomeTex.setText(cliente.getString("nome"));
            this.telText.setText(cliente.getString("telefone"));
            this.cpfTex.setText(cliente.getString("cpf"));
        }
            
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }
    
    
    public void preencheTabel() {
        try {
            ResultSet todos = bd.recupera("select * from tb_clientes");
            tCli.setNumRows(0);
            while (todos.next()) {
                String[] Nlinha = {
                    todos.getString("id"),
                    todos.getString("nome"),
                    todos.getString("telefone"),
                    todos.getString("cpf"),
                    "            X", "            O"
                };
                tCli.addRow(Nlinha);
            }
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }

    public ResultSet busca() {
        return bd.recupera("select * from tb_clientes");
    }
    
    public void limpar() {
        this.idSelect = "";
        this.nomeTex.setText("");
        this.telText.setText("");
        this.cpfTex.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JTable clienteTab;
    private javax.swing.JTextField cpfTex;
    private javax.swing.JToggleButton guardarBt;
    private javax.swing.JPanel homeP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton limparBt;
    private javax.swing.JTextField nomeTex;
    private javax.swing.JTextField telText;
    // End of variables declaration//GEN-END:variables
private String idSelect = "";
}
